### ISSUE TITLE
html5 validation don't work

### ISSUE THREAD

**Issue by KernelFolla** [jhollingworth/bootstrap-wysihtml5#275]
html5 validation (required="required" for example) don't work.
this appens because the original field is hidden.

this is my workaround, I hope it can be useful:)

``` javascript
    jQuery('.wysihtml5').wysihtml5({
        "events":      {
            "load": function () {
                jQuery('.wysihtml5').addClass('nicehide');
            }
        }
    });
```

``` css
.nicehide {
    resize: none;
    display: block !important;
    width: 0;
    height: 0;
    margin: 0 0 0 -15px;
    float: left;
    border: none;
}
```
